version: "3"

services:
  api-solid-pg:
    container_name: api-solid-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432 # first is host port, second is container port
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
