name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-solid-mariadb:
        image: bitnami/mariadb:latest
        ports:
          - 3307:3306
        env:
          MARIADB_ROOT_USER: root
          MARIADB_ROOT_PASSWORD: rootpassword
          MARIADB_USER: mysql
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: apisolid

      api-solid-mariadb-shadow:
        image: bitnami/mariadb:latest
        ports:
          - 3308:3306
        env:
          MARIADB_ROOT_USER: root
          MARIADB_ROOT_PASSWORD: rootpassword
          MARIADB_USER: mysql
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: apisolidShadow

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: "secret"
          DATABASE_URL: "mysql://root:rootpassword@localhost:3307/apisolid"
          SHADOW_DATABASE_URL: "mysql://root:rootpassword@localhost:3308/apisolidShadow"
